### ISSUE TITLE
Rise of Tomb Raider - sigsegv(11) crash

### ISSUE THREAD

**Issue by Ancient8** [FeralInteractive/gamemode#305]
**Describe the bug**
I installed ROTR and set gamemoderun %command% on the launch options, after I launch it natively It launches the first window where you can set some settings, after I hit play it starts and crashes immediately afterwards with the following message:

![Screenshot from 2020-12-12 15-36-38](https://user-images.githubusercontent.com/75816348/101988160-da932b80-3c8f-11eb-828c-6674bf6c3a5d.png)

If I disable the launch command of gamemoderun it doesn't crash anymore.

**To Reproduce**
Steps used to reproduce the behavior:
1. Set gamemoderun %command%
2. Run game.
3. Hit play on the setup window.
4. Shows error sigsegv(11) and crashes.

**Expected behavior**
After enabling 'gamemoderun %command%' on Steam launch options in ROTR it should run natively without crashing at startup.

**System Info (please complete the following information):**
 - OS and version: Ubuntu 20.04.1 LTS
 - GameMode Version v1.5.1

**Additional context**
CPU: AMD Ryzen 5 3600x
GPU: Asus GTX 1660 Super OC EVO
Nvidia driver: 455.38

**Comment by Ancient8** [comment]
Update: When i play it without gamemoderun %command%, although it doesn't crash at the start it can sometimes crash later on too at random times, giving the same error.

**Comment by eagleivg** [comment]
I have same issue, crash with sigsegv
```
$ lsb_release -a
LSB Version:	core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```

**Comment by eagleivg** [comment]
Run with gdb, but IDK where debug info...
`[Detaching after vfork from child process 116601]
--Type <RET> for more, q to quit, c to continue without paging--

Thread 54 "WinMain" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffee9246700 (LWP 116567)]
0x00000000007c4408 in ?? ()
(gdb) bt
#0  0x00000000007c4408 in  ()
#1  0x00000000007cfabc in  ()
#2  0x0000000000777732 in  ()
#3  0x0000000001cd26ad in  ()
#4  0x0000000001d68989 in  ()
#5  0x0000000001cee6ad in  ()
#6  0x0000000001ceeb96 in  ()
#7  0x0000000001ce161e in  ()
#8  0x0000000000785dce in  ()
#9  0x0000000000787dc5 in  ()
#10 0x000000000098a955 in  ()
#11 0x00000000009927ba in  ()
#12 0x00000000009a3d89 in  ()
#13 0x00000000005265a1 in WinMain ()
#14 0x000000000174f65d in  ()
#15 0x00007ffff76b5609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#16 0x00007ffff219a163 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
`
