### ISSUE TITLE
bootstrap.sh fails on ubuntu 18.04 beta

### ISSUE THREAD

**Issue by m-svo** [FeralInteractive/gamemode#36]
Hello!
Since it is beta, do you want me to post output and create an issue, or should I wait till release and check then?

**Comment by mdiluz** [comment]
Hi :)

Might as well report what's going on here, `18.04` is an RC now so things should work.

**Comment by m-svo** [comment]
Thanks! Here it is:

ubuntu@Ubuntu:~/gamemode-1.0$ ./bootstrap.sh 
+ meson --prefix=/usr build -Dwith-systemd-user-unit-dir=/etc/systemd/user
The Meson build system
Version: 0.45.1
Source dir: /home/svobonas/gamemode-1.0
Build dir: /home/svobonas/gamemode-1.0/build
Build type: native build
Project name: gamemode
Native C compiler: cc (gcc 7.3.0 "cc (Ubuntu 7.3.0-16ubuntu3) 7.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency libsystemd found: YES 237
Dependency threads found: YES
Library dl found: YES
Configuring config.h using configuration
Traceback (most recent call last):
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 361, in run
    app.generate()
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 150, in generate
    self._generate(env)
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 197, in _generate
    intr.run()
  File "/usr/share/meson/mesonbuild/interpreter.py", line 2991, in run
    super().run()
  File "/usr/share/meson/mesonbuild/interpreterbase.py", line 173, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/usr/share/meson/mesonbuild/interpreterbase.py", line 195, in evaluate_codeblock
    raise e
  File "/usr/share/meson/mesonbuild/interpreterbase.py", line 189, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/share/meson/mesonbuild/interpreterbase.py", line 210, in evaluate_statement
    return self.evaluate_if(cur)
  File "/usr/share/meson/mesonbuild/interpreterbase.py", line 263, in evaluate_if
    self.evaluate_codeblock(i.block)
  File "/usr/share/meson/mesonbuild/interpreterbase.py", line 195, in evaluate_codeblock
    raise e
  File "/usr/share/meson/mesonbuild/interpreterbase.py", line 189, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/share/meson/mesonbuild/interpreterbase.py", line 202, in evaluate_statement
    return self.assignment(cur)
  File "/usr/share/meson/mesonbuild/interpreterbase.py", line 674, in assignment
    value = self.evaluate_statement(node.value)
  File "/usr/share/meson/mesonbuild/interpreterbase.py", line 200, in evaluate_statement
    return self.function_call(cur)
  File "/usr/share/meson/mesonbuild/interpreterbase.py", line 456, in function_call
    return self.funcs[func_name](node, self.flatten(posargs), kwargs)
  File "/usr/share/meson/mesonbuild/interpreterbase.py", line 79, in wrapped
    return f(s, node_or_state, args, kwargs)
  File "/usr/share/meson/mesonbuild/interpreterbase.py", line 55, in wrapped
    return f(self, node, args, kwargs)
  File "/usr/share/meson/mesonbuild/interpreter.py", line 1742, in func_subproject
    return self.do_subproject(dirname, kwargs)
  File "/usr/share/meson/mesonbuild/interpreter.py", line 1764, in do_subproject
    resolved = r.resolve(dirname)
  File "/usr/share/meson/mesonbuild/wrap/wrap.py", line 126, in resolve
    if self.resolve_git_submodule(dirname):
  File "/usr/share/meson/mesonbuild/wrap/wrap.py", line 159, in resolve_git_submodule
    ret, out = quiet_git(['rev-parse'], self.subdir_root)
  File "/usr/share/meson/mesonbuild/wrap/wrap.py", line 44, in quiet_git
    stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git': 'git'

**Comment by mdiluz** [comment]
Hmm, does `apt install git` resolve that?

**Comment by m-svo** [comment]
Yes! Thanks a lot!
