### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/home/yufes/gamemode/builddir'

### ISSUE THREAD

**Issue by yusufemrekaraca** [FeralInteractive/gamemode#409]
i'm trying to execute "./bootstrap.sh" but it give me an error like : 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/mesonbuild/mesonmain.py", line 193, in run
    return options.run_func(options)
  File "/usr/local/lib/python3.10/dist-packages/mesonbuild/msetup.py", line 308, in run
    app = MesonApp(options)
  File "/usr/local/lib/python3.10/dist-packages/mesonbuild/msetup.py", line 77, in __init__
    (self.source_dir, self.build_dir) = self.validate_dirs(options.builddir,
  File "/usr/local/lib/python3.10/dist-packages/mesonbuild/msetup.py", line 161, in validate_dirs
    (src_dir, build_dir) = self.validate_core_dirs(dir1, dir2)
  File "/usr/local/lib/python3.10/dist-packages/mesonbuild/msetup.py", line 132, in validate_core_dirs
    os.makedirs(ndir1)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/yufes/gamemode/builddir'

ERROR: Unhandled python OSError. This is probably not a Meson bug, but an issue with your build environment.
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
```
i'm not really sure how to fix it,i tried reinstalling but it didn't work.

**Comment by Tonklaistonton** [comment]
same issus
