### ISSUE TITLE
can not build gamemode on linux

### ISSUE THREAD

**Issue by Bladeofgodol** [FeralInteractive/gamemode#413]
I am not sure if its system specific on an arch once the repo is cloned as a .xz file it is not possible to build. i have made sure to install all dependencies and simply copy and past the build and install commands.

Steps used to reproduce the behavior:
on an arch linux follow the guide

**Expected behavior**
completed compilation and install

**System Info (please complete the following information):**
 - OS and version: [arch linux 6.2.1]
 - GameMode Version [git sha]

**Additional context**
``` 
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
+ ninja -C builddir
ninja: Entering directory `builddir'
[3/22] Compiling C object common/liblib-common.a.p/common-pidfds.c.o
FAILED: common/liblib-common.a.p/common-pidfds.c.o
cc -Icommon/liblib-common.a.p -Icommon -I../common -I. -I.. -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -std=c11 -O2 -g -fstack-protector -Wstrict-prototypes -Wundef -fno-common -Werror-implicit-function-declaration -Wformat-security -Werror=format-security -Wconversion -Wunreachable-code -Waggregate-return -Wunused -Warray-bounds -Wcast-align -Wclobbered -Wempty-body -Wformat=2 -Wformat-nonliteral -Wformat-signedness -Wignored-qualifiers -Wimplicit-function-declaration -Winit-self -Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-noreturn -Wmissing-parameter-type -Wnested-externs -Wno-discarded-qualifiers -Wno-missing-field-initializers -Wno-suggest-attribute=format -Wno-unused-parameter -Wold-style-definition -Woverride-init -Wpointer-arith -Wredundant-decls -Wreturn-type -Wshadow -Wsign-compare -Wstrict-aliasing=3 -Wstrict-prototypes -Wstringop-overflow -Wstringop-truncation -Wtype-limits -Wundef -Wuninitialized -Wunused-but-set-variable -Wwrite-strings -fPIC -MD -MQ common/liblib-common.a.p/common-pidfds.c.o -MF common/liblib-common.a.p/common-pidfds.c.o.d -o common/liblib-common.a.p/common-pidfds.c.o -c ../common/common-pidfds.c
../common/common-pidfds.c: In function ‘open_pidfds’:
../common/common-pidfds.c:70:26: error: implicit declaration of function ‘pidfd_open’; did you mean ‘fdopen’? [-Werror=implicit-function-declaration]
   70 |                 int fd = pidfd_open(pid, 0);
      |                          ^~~~~~~~~~
      |                          fdopen
../common/common-pidfds.c:70:26: warning: nested extern declaration of ‘pidfd_open’ [-Wnested-externs]
cc1: some warnings being treated as errors
[5/22] Compiling C object common/libdaemon-common.a.p/common-pidfds.c.o
FAILED: common/libdaemon-common.a.p/common-pidfds.c.o
cc -Icommon/libdaemon-common.a.p -Icommon -I../common -I. -I.. -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -std=c11 -O2 -g -fstack-protector -Wstrict-prototypes -Wundef -fno-common -Werror-implicit-function-declaration -Wformat-security -Werror=format-security -Wconversion -Wunreachable-code -Waggregate-return -Wunused -Warray-bounds -Wcast-align -Wclobbered -Wempty-body -Wformat=2 -Wformat-nonliteral -Wformat-signedness -Wignored-qualifiers -Wimplicit-function-declaration -Winit-self -Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-noreturn -Wmissing-parameter-type -Wnested-externs -Wno-discarded-qualifiers -Wno-missing-field-initializers -Wno-suggest-attribute=format -Wno-unused-parameter -Wold-style-definition -Woverride-init -Wpointer-arith -Wredundant-decls -Wreturn-type -Wshadow -Wsign-compare -Wstrict-aliasing=3 -Wstrict-prototypes -Wstringop-overflow -Wstringop-truncation -Wtype-limits -Wundef -Wuninitialized -Wunused-but-set-variable -Wwrite-strings -fPIC -MD -MQ common/libdaemon-common.a.p/common-pidfds.c.o -MF common/libdaemon-common.a.p/common-pidfds.c.o.d -o common/libdaemon-common.a.p/common-pidfds.c.o -c ../common/common-pidfds.c
../common/common-pidfds.c: In function ‘open_pidfds’:
../common/common-pidfds.c:70:26: error: implicit declaration of function ‘pidfd_open’; did you mean ‘fdopen’? [-Werror=implicit-function-declaration]
   70 |                 int fd = pidfd_open(pid, 0);
      |                          ^~~~~~~~~~
      |                          fdopen
../common/common-pidfds.c:70:26: warning: nested extern declaration of ‘pidfd_open’ [-Wnested-externs]
cc1: some warnings being treated as errors
[8/22] Compiling C object daemon/gamemoded.p/gamemoded.c.o
ninja: build stopped: subcommand failed.

```
im assuming that the pidfd_open function has been removed or moved with the update of glibc from 2.36 to 2.37

**Comment by DumbledoreCalrissian** [comment]
I have the same issue in Arch 6.2.11 (followed instructions in the readme)

**Comment by WaffleSlapper** [comment]
Same issue on my Arch 6.1.25. 
If it helps at all... This issue only shows up when using the 1.7 game mode as instructed from the README. There is a new error that gets spit out if you try out with the master branch.

```
+ ninja -C builddir
ninja: Entering directory `builddir'
[31/31] Linking target daemon/gamemoded
+ set +x
Install to /usr? [y/N] y
+ sudo ninja install -C builddir
ninja: Entering directory `builddir'
[0/1] Installing files.
Traceback (most recent call last):
  File "/home/user/.local/bin/meson", line 5, in <module>
    from mesonbuild.mesonmain import main
ModuleNotFoundError: No module named 'mesonbuild.mesonmain'
FAILED: meson-internal__install 
/home/user/.local/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
```

**Comment by BearsPunch** [comment]
Looks like **#if !HAVE_FN_PIDFD_OPEN** doesn't work now. So I was able to build app by manually move this code from if statement 
```
#define __NR_pidfd_open 434
static int pidfd_open(pid_t pid, unsigned int flags)
{
	return (int)syscall(__NR_pidfd_open, pid, flags);
}
```

**Comment by WaffleSlapper** [comment]
> Same issue on my Arch 6.1.25. If it helps at all... This issue only shows up when using the 1.7 game mode as instructed from the README. There is a new error that gets spit out if you try out with the master branch.
> 
> ```
> + ninja -C builddir
> ninja: Entering directory `builddir'
> [31/31] Linking target daemon/gamemoded
> + set +x
> Install to /usr? [y/N] y
> + sudo ninja install -C builddir
> ninja: Entering directory `builddir'
> [0/1] Installing files.
> Traceback (most recent call last):
>   File "/home/user/.local/bin/meson", line 5, in <module>
>     from mesonbuild.mesonmain import main
> ModuleNotFoundError: No module named 'mesonbuild.mesonmain'
> FAILED: meson-internal__install 
> /home/user/.local/bin/meson install --no-rebuild
> ninja: build stopped: subcommand failed.
> ```

For this particular error:
```
ModuleNotFoundError: No module named 'mesonbuild.mesonmain'
```
I solved this issue by installing meson in root. It was the only way ninja was able to find the module. Following[ this answer](https://github.com/mesonbuild/meson/issues/7258#issuecomment-703920433):
``` 
sudo -i 
pip3 install meson
```
Then I ran `bootstrap.sh` in the `master` branch. gamemode 1.7 has outdated functions and should no longer be in the readme in my opinion.

If you want to keep the 1.7 version you would need to do a few adjustments to keep it working. 
When you run it you will get the error @Bladeofgodol  posted. You would have to follow the advice that the prompt gives you:
```
../common/common-pidfds.c:70:26: error: implicit declaration of function ‘pidfd_open’; did you mean ‘fdopen’? [-Werror=implicit-function-declaration]
```  
and go into the `/common/common-pidfds.c` file and change all `pidfd_open` functions to 'fdopen'.

Then you would need to go into the `bootstrap.sh` script and [implement this fix](https://github.com/8lendzior/gamemode/commit/9b5fb648f0fc850e34f413ce60d6211ea6624621)  Which was has been merged into master.

**Comment by fury861** [comment]
Updating kernel and installing kernel-headers worked for me (in ARCH)
