### ISSUE TITLE
Gamemoded fails tests (gamemode failed to deactivate when requested)

### ISSUE THREAD

**Issue by awsms** [FeralInteractive/gamemode#435]
**Describe the bug**
Gamemoded fails the tests when running gamemoded -t.

**To Reproduce**
Steps used to reproduce the behavior:
1. Install gamemode from the AUR (tried both gamemode & gamemode-git)
2. Run gamemoded -t
3. Fails

**Expected behavior**
Gamemode shoud pass all the tests.

**System Info (please complete the following information):**
 - EndeavourOS
 - GameMode Version git & 1.7

**Additional context**
Logs output:
```: Loading config
Loading config file [/usr/share/gamemode/gamemode.ini]
Loading config file [/etc/gamemode.ini]
: Running tests

:: Basic client tests
:: Passed

:: Dual client tests
gamemode request succeeded and is active
Quitting by request...
:: Passed

:: Gamemoderun and reaper thread tests
...Waiting for child to quit...
...Waiting for reaper thread (reaper_frequency set to 5 seconds)...
ERROR: gamemode failed to deactivate when requested (expected 0)!
:: Supervisor tests
ERROR: gamemode_query_status after end request gave unexpected value 1, (expected 0)!
ERROR: :: Failed!
: Client tests failed, skipping feature tests
: Tests Failed!

**Comment by pwfff** [comment]
also getting this... sometimes. it's associated with a coredump in my logs:
```
Core was generated by `sleep 5'.
Program terminated with signal SIGABRT, Aborted.
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
44	     return INTERNAL_SYSCALL_ERROR_P (ret) ? INTERNAL_SYSCALL_ERRNO (ret) : 0;                                                                                              
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007f65910ab8a3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007f659105b668 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007f65910434b8 in __GI_abort () at abort.c:79
#4  0x00007f6590fd0044 in _dbus_abort () at /usr/src/debug/dbus/dbus/dbus/dbus-sysdeps.c:101
#5  0x00007f6590ff78eb in _dbus_warn_check_failed (
    format=0x7f6591003080 "arguments to %s() were incorrect, assertion \"%s\" failed in file %s line %d.\nThis is normally a bug in some application using the D-Bus library.\n")
    at /usr/src/debug/dbus/dbus/dbus/dbus-internals.c:289
#6  0x00007f6591015bfd in make_request (bus=0x5603eef7e3d0, native=1, use_pidfds=0, method=0x7f6591017231 "UnregisterGame", pids=0x7ffd57103d38, npids=1, error=0x7ffd57103d40)
    at ../lib/client_impl.c:268
#7  0x00007f6591015e5d in gamemode_request (method=0x7f6591017231 "UnregisterGame", for_pid=0) at ../lib/client_impl.c:339
#8  0x00007f6591015f42 in real_gamemode_request_end () at ../lib/client_impl.c:374
#9  0x00007f65912013c0 in gamemode_request_end () at ../lib/gamemode_client.h:294
#10 0x00007f65912510e2 in _dl_call_fini (closure_map=closure_map@entry=0x7f659124e070) at dl-call_fini.c:43
#11 0x00007f6591254d9c in _dl_fini () at dl-fini.c:78
#12 0x00007f659105dcc6 in __run_exit_handlers (status=0, listp=0x7f65911f5680 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true)
    at exit.c:111
#13 0x00007f659105de10 in __GI_exit (status=<optimized out>) at exit.c:141
#14 0x00007f6591044cd7 in __libc_start_call_main (main=main@entry=0x5603ee957030 <main>, argc=argc@entry=2, argv=argv@entry=0x7ffd57104128)
    at ../sysdeps/nptl/libc_start_call_main.h:74
#15 0x00007f6591044d8a in __libc_start_main_impl (main=0x5603ee957030 <main>, argc=2, argv=0x7ffd57104128, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7ffd57104118) at ../csu/libc-start.c:360
#16 0x00005603ee957665 in _start ()
```

running with `DBUS_FATAL_WARNINGS=0` stops it from dumping, but I can't find the error/warning message printed out anywhere. also of note is that `call` is `0x0`:
```
(gdb) f 5
#5  0x00007f6591015bfd in make_request (bus=0x5603eef7e3d0, native=1, use_pidfds=0, method=0x7f6591017231 "UnregisterGame", pids=0x7ffd57103d38, npids=1, error=0x7ffd57103d40)
    at ../lib/client_impl.c:268
268		dbus_pending_call_block(call);
(gdb) print call
$1 = (DBusPendingCall *) 0x0
```

**Comment by pwfff** [comment]
like I said, it's only *sometimes*:
```
[pwf@prism gamemode]$ gamemoded -t
: Loading config
Loading config file [/usr/share/gamemode/gamemode.ini]
Loading config file [/etc/gamemode.ini]
: Running tests

:: Basic client tests
:: Passed

:: Dual client tests
gamemode request succeeded and is active
Quitting by request...
:: Passed

:: Gamemoderun and reaper thread tests
...Waiting for child to quit...
...Waiting for reaper thread (reaper_frequency set to 6 seconds)...
:: Passed

:: Supervisor tests
:: Passed

:: Feature tests
::: Verifying CPU governor setting
::: Passed
::: Verifying Scripts
::: Passed (no scripts configured to run)
::: Verifying GPU Optimisations
::: Passed (gpu optimisations not configured to run)
::: Verifying renice
::: Passed
::: Verifying ioprio
::: Passed
:: Passed

: All Tests Passed!
[pwf@prism gamemode]$ gamemoded -t
: Loading config
Loading config file [/usr/share/gamemode/gamemode.ini]
Loading config file [/etc/gamemode.ini]
: Running tests

:: Basic client tests
:: Passed

:: Dual client tests
gamemode request succeeded and is active
Quitting by request...
:: Passed

:: Gamemoderun and reaper thread tests
...Waiting for child to quit...
...Waiting for reaper thread (reaper_frequency set to 6 seconds)...
:: Passed

:: Supervisor tests
:: Passed

:: Feature tests
::: Verifying CPU governor setting
::: Passed
::: Verifying Scripts
::: Passed (no scripts configured to run)
::: Verifying GPU Optimisations
::: Passed (gpu optimisations not configured to run)
::: Verifying renice
::: Passed
::: Verifying ioprio
::: Passed
:: Passed

: All Tests Passed!
[pwf@prism gamemode]$ gamemoded -t
: Loading config
Loading config file [/usr/share/gamemode/gamemode.ini]
Loading config file [/etc/gamemode.ini]
: Running tests

:: Basic client tests
:: Passed

:: Dual client tests
gamemode request succeeded and is active
Quitting by request...
:: Passed

:: Gamemoderun and reaper thread tests
...Waiting for child to quit...
...Waiting for reaper thread (reaper_frequency set to 6 seconds)...
ERROR: gamemode failed to deactivate when requested (expected 0)!
:: Supervisor tests
ERROR: gamemode_query_status after end request gave unexpected value 1, (expected 0)!
ERROR: :: Failed!
: Client tests failed, skipping feature tests
: Tests Failed!
```

race condition?
